/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.torproject.metrics.converTor.relayExtra;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ConnBiDirect extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConnBiDirect\",\"namespace\":\"org.torproject.metrics.converTor.relayExtra\",\"fields\":[{\"name\":\"date\",\"type\":[\"null\",\"string\"]},{\"name\":\"interval\",\"type\":\"long\",\"default\":86400},{\"name\":\"below\",\"type\":[\"null\",\"int\"]},{\"name\":\"read\",\"type\":[\"null\",\"int\"]},{\"name\":\"write\",\"type\":[\"null\",\"int\"]},{\"name\":\"both\",\"type\":[\"null\",\"int\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence date;
  @Deprecated public long interval;
  @Deprecated public java.lang.Integer below;
  @Deprecated public java.lang.Integer read;
  @Deprecated public java.lang.Integer write;
  @Deprecated public java.lang.Integer both;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ConnBiDirect() {}

  /**
   * All-args constructor.
   */
  public ConnBiDirect(java.lang.CharSequence date, java.lang.Long interval, java.lang.Integer below, java.lang.Integer read, java.lang.Integer write, java.lang.Integer both) {
    this.date = date;
    this.interval = interval;
    this.below = below;
    this.read = read;
    this.write = write;
    this.both = both;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return date;
    case 1: return interval;
    case 2: return below;
    case 3: return read;
    case 4: return write;
    case 5: return both;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: date = (java.lang.CharSequence)value$; break;
    case 1: interval = (java.lang.Long)value$; break;
    case 2: below = (java.lang.Integer)value$; break;
    case 3: read = (java.lang.Integer)value$; break;
    case 4: write = (java.lang.Integer)value$; break;
    case 5: both = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'interval' field.
   */
  public java.lang.Long getInterval() {
    return interval;
  }

  /**
   * Sets the value of the 'interval' field.
   * @param value the value to set.
   */
  public void setInterval(java.lang.Long value) {
    this.interval = value;
  }

  /**
   * Gets the value of the 'below' field.
   */
  public java.lang.Integer getBelow() {
    return below;
  }

  /**
   * Sets the value of the 'below' field.
   * @param value the value to set.
   */
  public void setBelow(java.lang.Integer value) {
    this.below = value;
  }

  /**
   * Gets the value of the 'read' field.
   */
  public java.lang.Integer getRead() {
    return read;
  }

  /**
   * Sets the value of the 'read' field.
   * @param value the value to set.
   */
  public void setRead(java.lang.Integer value) {
    this.read = value;
  }

  /**
   * Gets the value of the 'write' field.
   */
  public java.lang.Integer getWrite() {
    return write;
  }

  /**
   * Sets the value of the 'write' field.
   * @param value the value to set.
   */
  public void setWrite(java.lang.Integer value) {
    this.write = value;
  }

  /**
   * Gets the value of the 'both' field.
   */
  public java.lang.Integer getBoth() {
    return both;
  }

  /**
   * Sets the value of the 'both' field.
   * @param value the value to set.
   */
  public void setBoth(java.lang.Integer value) {
    this.both = value;
  }

  /** Creates a new ConnBiDirect RecordBuilder */
  public static org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder newBuilder() {
    return new org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder();
  }
  
  /** Creates a new ConnBiDirect RecordBuilder by copying an existing Builder */
  public static org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder newBuilder(org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder other) {
    return new org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder(other);
  }
  
  /** Creates a new ConnBiDirect RecordBuilder by copying an existing ConnBiDirect instance */
  public static org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder newBuilder(org.torproject.metrics.converTor.relayExtra.ConnBiDirect other) {
    return new org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder(other);
  }
  
  /**
   * RecordBuilder for ConnBiDirect instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConnBiDirect>
    implements org.apache.avro.data.RecordBuilder<ConnBiDirect> {

    private java.lang.CharSequence date;
    private long interval;
    private java.lang.Integer below;
    private java.lang.Integer read;
    private java.lang.Integer write;
    private java.lang.Integer both;

    /** Creates a new Builder */
    private Builder() {
      super(org.torproject.metrics.converTor.relayExtra.ConnBiDirect.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.interval)) {
        this.interval = data().deepCopy(fields()[1].schema(), other.interval);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.below)) {
        this.below = data().deepCopy(fields()[2].schema(), other.below);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.read)) {
        this.read = data().deepCopy(fields()[3].schema(), other.read);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.write)) {
        this.write = data().deepCopy(fields()[4].schema(), other.write);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.both)) {
        this.both = data().deepCopy(fields()[5].schema(), other.both);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ConnBiDirect instance */
    private Builder(org.torproject.metrics.converTor.relayExtra.ConnBiDirect other) {
            super(org.torproject.metrics.converTor.relayExtra.ConnBiDirect.SCHEMA$);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.interval)) {
        this.interval = data().deepCopy(fields()[1].schema(), other.interval);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.below)) {
        this.below = data().deepCopy(fields()[2].schema(), other.below);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.read)) {
        this.read = data().deepCopy(fields()[3].schema(), other.read);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.write)) {
        this.write = data().deepCopy(fields()[4].schema(), other.write);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.both)) {
        this.both = data().deepCopy(fields()[5].schema(), other.both);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'date' field */
    public java.lang.CharSequence getDate() {
      return date;
    }
    
    /** Sets the value of the 'date' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.date = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'date' field has been set */
    public boolean hasDate() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'date' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder clearDate() {
      date = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'interval' field */
    public java.lang.Long getInterval() {
      return interval;
    }
    
    /** Sets the value of the 'interval' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder setInterval(long value) {
      validate(fields()[1], value);
      this.interval = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'interval' field has been set */
    public boolean hasInterval() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'interval' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder clearInterval() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'below' field */
    public java.lang.Integer getBelow() {
      return below;
    }
    
    /** Sets the value of the 'below' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder setBelow(java.lang.Integer value) {
      validate(fields()[2], value);
      this.below = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'below' field has been set */
    public boolean hasBelow() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'below' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder clearBelow() {
      below = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'read' field */
    public java.lang.Integer getRead() {
      return read;
    }
    
    /** Sets the value of the 'read' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder setRead(java.lang.Integer value) {
      validate(fields()[3], value);
      this.read = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'read' field has been set */
    public boolean hasRead() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'read' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder clearRead() {
      read = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'write' field */
    public java.lang.Integer getWrite() {
      return write;
    }
    
    /** Sets the value of the 'write' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder setWrite(java.lang.Integer value) {
      validate(fields()[4], value);
      this.write = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'write' field has been set */
    public boolean hasWrite() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'write' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder clearWrite() {
      write = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'both' field */
    public java.lang.Integer getBoth() {
      return both;
    }
    
    /** Sets the value of the 'both' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder setBoth(java.lang.Integer value) {
      validate(fields()[5], value);
      this.both = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'both' field has been set */
    public boolean hasBoth() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'both' field */
    public org.torproject.metrics.converTor.relayExtra.ConnBiDirect.Builder clearBoth() {
      both = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public ConnBiDirect build() {
      try {
        ConnBiDirect record = new ConnBiDirect();
        record.date = fieldSetFlags()[0] ? this.date : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.interval = fieldSetFlags()[1] ? this.interval : (java.lang.Long) defaultValue(fields()[1]);
        record.below = fieldSetFlags()[2] ? this.below : (java.lang.Integer) defaultValue(fields()[2]);
        record.read = fieldSetFlags()[3] ? this.read : (java.lang.Integer) defaultValue(fields()[3]);
        record.write = fieldSetFlags()[4] ? this.write : (java.lang.Integer) defaultValue(fields()[4]);
        record.both = fieldSetFlags()[5] ? this.both : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
