/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.torproject.metrics.converTor.relayConsensus;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Router extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Router\",\"namespace\":\"org.torproject.metrics.converTor.relayConsensus\",\"fields\":[{\"name\":\"r\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"R\",\"fields\":[{\"name\":\"nickname\",\"type\":[\"null\",\"string\"]},{\"name\":\"identity\",\"type\":[\"null\",\"string\"]},{\"name\":\"digest\",\"type\":[\"null\",\"string\"]},{\"name\":\"publication\",\"type\":[\"null\",\"string\"]},{\"name\":\"ip\",\"type\":[\"null\",\"string\"]},{\"name\":\"or_port\",\"type\":[\"null\",\"int\"]},{\"name\":\"dir_port\",\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"a\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"s\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"v\",\"type\":[\"null\",\"string\"]},{\"name\":\"w\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"W\",\"fields\":[{\"name\":\"bandwidth\",\"type\":[\"null\",\"long\"]},{\"name\":\"measured\",\"type\":[\"null\",\"long\"]},{\"name\":\"unmeasured\",\"type\":[\"null\",\"boolean\"]}]}]},{\"name\":\"p\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Policy\",\"fields\":[{\"name\":\"default_policy\",\"type\":[\"null\",\"string\"]},{\"name\":\"port_summary\",\"type\":[\"null\",\"string\"]}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public org.torproject.metrics.converTor.relayConsensus.R r;
  @Deprecated public java.util.List<java.lang.CharSequence> a;
  @Deprecated public java.util.List<java.lang.CharSequence> s;
  @Deprecated public java.lang.CharSequence v;
  @Deprecated public org.torproject.metrics.converTor.relayConsensus.W w;
  @Deprecated public org.torproject.metrics.converTor.relayConsensus.Policy p;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Router() {}

  /**
   * All-args constructor.
   */
  public Router(org.torproject.metrics.converTor.relayConsensus.R r, java.util.List<java.lang.CharSequence> a, java.util.List<java.lang.CharSequence> s, java.lang.CharSequence v, org.torproject.metrics.converTor.relayConsensus.W w, org.torproject.metrics.converTor.relayConsensus.Policy p) {
    this.r = r;
    this.a = a;
    this.s = s;
    this.v = v;
    this.w = w;
    this.p = p;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return r;
    case 1: return a;
    case 2: return s;
    case 3: return v;
    case 4: return w;
    case 5: return p;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: r = (org.torproject.metrics.converTor.relayConsensus.R)value$; break;
    case 1: a = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: s = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: v = (java.lang.CharSequence)value$; break;
    case 4: w = (org.torproject.metrics.converTor.relayConsensus.W)value$; break;
    case 5: p = (org.torproject.metrics.converTor.relayConsensus.Policy)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'r' field.
   */
  public org.torproject.metrics.converTor.relayConsensus.R getR() {
    return r;
  }

  /**
   * Sets the value of the 'r' field.
   * @param value the value to set.
   */
  public void setR(org.torproject.metrics.converTor.relayConsensus.R value) {
    this.r = value;
  }

  /**
   * Gets the value of the 'a' field.
   */
  public java.util.List<java.lang.CharSequence> getA() {
    return a;
  }

  /**
   * Sets the value of the 'a' field.
   * @param value the value to set.
   */
  public void setA(java.util.List<java.lang.CharSequence> value) {
    this.a = value;
  }

  /**
   * Gets the value of the 's' field.
   */
  public java.util.List<java.lang.CharSequence> getS() {
    return s;
  }

  /**
   * Sets the value of the 's' field.
   * @param value the value to set.
   */
  public void setS(java.util.List<java.lang.CharSequence> value) {
    this.s = value;
  }

  /**
   * Gets the value of the 'v' field.
   */
  public java.lang.CharSequence getV() {
    return v;
  }

  /**
   * Sets the value of the 'v' field.
   * @param value the value to set.
   */
  public void setV(java.lang.CharSequence value) {
    this.v = value;
  }

  /**
   * Gets the value of the 'w' field.
   */
  public org.torproject.metrics.converTor.relayConsensus.W getW() {
    return w;
  }

  /**
   * Sets the value of the 'w' field.
   * @param value the value to set.
   */
  public void setW(org.torproject.metrics.converTor.relayConsensus.W value) {
    this.w = value;
  }

  /**
   * Gets the value of the 'p' field.
   */
  public org.torproject.metrics.converTor.relayConsensus.Policy getP() {
    return p;
  }

  /**
   * Sets the value of the 'p' field.
   * @param value the value to set.
   */
  public void setP(org.torproject.metrics.converTor.relayConsensus.Policy value) {
    this.p = value;
  }

  /** Creates a new Router RecordBuilder */
  public static org.torproject.metrics.converTor.relayConsensus.Router.Builder newBuilder() {
    return new org.torproject.metrics.converTor.relayConsensus.Router.Builder();
  }
  
  /** Creates a new Router RecordBuilder by copying an existing Builder */
  public static org.torproject.metrics.converTor.relayConsensus.Router.Builder newBuilder(org.torproject.metrics.converTor.relayConsensus.Router.Builder other) {
    return new org.torproject.metrics.converTor.relayConsensus.Router.Builder(other);
  }
  
  /** Creates a new Router RecordBuilder by copying an existing Router instance */
  public static org.torproject.metrics.converTor.relayConsensus.Router.Builder newBuilder(org.torproject.metrics.converTor.relayConsensus.Router other) {
    return new org.torproject.metrics.converTor.relayConsensus.Router.Builder(other);
  }
  
  /**
   * RecordBuilder for Router instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Router>
    implements org.apache.avro.data.RecordBuilder<Router> {

    private org.torproject.metrics.converTor.relayConsensus.R r;
    private java.util.List<java.lang.CharSequence> a;
    private java.util.List<java.lang.CharSequence> s;
    private java.lang.CharSequence v;
    private org.torproject.metrics.converTor.relayConsensus.W w;
    private org.torproject.metrics.converTor.relayConsensus.Policy p;

    /** Creates a new Builder */
    private Builder() {
      super(org.torproject.metrics.converTor.relayConsensus.Router.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.torproject.metrics.converTor.relayConsensus.Router.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.r)) {
        this.r = data().deepCopy(fields()[0].schema(), other.r);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.a)) {
        this.a = data().deepCopy(fields()[1].schema(), other.a);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.s)) {
        this.s = data().deepCopy(fields()[2].schema(), other.s);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.v)) {
        this.v = data().deepCopy(fields()[3].schema(), other.v);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.w)) {
        this.w = data().deepCopy(fields()[4].schema(), other.w);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.p)) {
        this.p = data().deepCopy(fields()[5].schema(), other.p);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Router instance */
    private Builder(org.torproject.metrics.converTor.relayConsensus.Router other) {
            super(org.torproject.metrics.converTor.relayConsensus.Router.SCHEMA$);
      if (isValidValue(fields()[0], other.r)) {
        this.r = data().deepCopy(fields()[0].schema(), other.r);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.a)) {
        this.a = data().deepCopy(fields()[1].schema(), other.a);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.s)) {
        this.s = data().deepCopy(fields()[2].schema(), other.s);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.v)) {
        this.v = data().deepCopy(fields()[3].schema(), other.v);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.w)) {
        this.w = data().deepCopy(fields()[4].schema(), other.w);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.p)) {
        this.p = data().deepCopy(fields()[5].schema(), other.p);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'r' field */
    public org.torproject.metrics.converTor.relayConsensus.R getR() {
      return r;
    }
    
    /** Sets the value of the 'r' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder setR(org.torproject.metrics.converTor.relayConsensus.R value) {
      validate(fields()[0], value);
      this.r = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'r' field has been set */
    public boolean hasR() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'r' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder clearR() {
      r = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'a' field */
    public java.util.List<java.lang.CharSequence> getA() {
      return a;
    }
    
    /** Sets the value of the 'a' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder setA(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.a = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'a' field has been set */
    public boolean hasA() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'a' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder clearA() {
      a = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 's' field */
    public java.util.List<java.lang.CharSequence> getS() {
      return s;
    }
    
    /** Sets the value of the 's' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder setS(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.s = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 's' field has been set */
    public boolean hasS() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 's' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder clearS() {
      s = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'v' field */
    public java.lang.CharSequence getV() {
      return v;
    }
    
    /** Sets the value of the 'v' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder setV(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.v = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'v' field has been set */
    public boolean hasV() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'v' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder clearV() {
      v = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'w' field */
    public org.torproject.metrics.converTor.relayConsensus.W getW() {
      return w;
    }
    
    /** Sets the value of the 'w' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder setW(org.torproject.metrics.converTor.relayConsensus.W value) {
      validate(fields()[4], value);
      this.w = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'w' field has been set */
    public boolean hasW() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'w' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder clearW() {
      w = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'p' field */
    public org.torproject.metrics.converTor.relayConsensus.Policy getP() {
      return p;
    }
    
    /** Sets the value of the 'p' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder setP(org.torproject.metrics.converTor.relayConsensus.Policy value) {
      validate(fields()[5], value);
      this.p = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'p' field has been set */
    public boolean hasP() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'p' field */
    public org.torproject.metrics.converTor.relayConsensus.Router.Builder clearP() {
      p = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public Router build() {
      try {
        Router record = new Router();
        record.r = fieldSetFlags()[0] ? this.r : (org.torproject.metrics.converTor.relayConsensus.R) defaultValue(fields()[0]);
        record.a = fieldSetFlags()[1] ? this.a : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.s = fieldSetFlags()[2] ? this.s : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.v = fieldSetFlags()[3] ? this.v : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.w = fieldSetFlags()[4] ? this.w : (org.torproject.metrics.converTor.relayConsensus.W) defaultValue(fields()[4]);
        record.p = fieldSetFlags()[5] ? this.p : (org.torproject.metrics.converTor.relayConsensus.Policy) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
