/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package converTor.relayExtra;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ExtraInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExtraInfo\",\"namespace\":\"converTor.relayExtra\",\"fields\":[{\"name\":\"nickname\",\"type\":[\"null\",\"string\"]},{\"name\":\"fingerprint\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence nickname;
  @Deprecated public java.lang.CharSequence fingerprint;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ExtraInfo() {}

  /**
   * All-args constructor.
   */
  public ExtraInfo(java.lang.CharSequence nickname, java.lang.CharSequence fingerprint) {
    this.nickname = nickname;
    this.fingerprint = fingerprint;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nickname;
    case 1: return fingerprint;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nickname = (java.lang.CharSequence)value$; break;
    case 1: fingerprint = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'nickname' field.
   */
  public java.lang.CharSequence getNickname() {
    return nickname;
  }

  /**
   * Sets the value of the 'nickname' field.
   * @param value the value to set.
   */
  public void setNickname(java.lang.CharSequence value) {
    this.nickname = value;
  }

  /**
   * Gets the value of the 'fingerprint' field.
   */
  public java.lang.CharSequence getFingerprint() {
    return fingerprint;
  }

  /**
   * Sets the value of the 'fingerprint' field.
   * @param value the value to set.
   */
  public void setFingerprint(java.lang.CharSequence value) {
    this.fingerprint = value;
  }

  /** Creates a new ExtraInfo RecordBuilder */
  public static converTor.relayExtra.ExtraInfo.Builder newBuilder() {
    return new converTor.relayExtra.ExtraInfo.Builder();
  }
  
  /** Creates a new ExtraInfo RecordBuilder by copying an existing Builder */
  public static converTor.relayExtra.ExtraInfo.Builder newBuilder(converTor.relayExtra.ExtraInfo.Builder other) {
    return new converTor.relayExtra.ExtraInfo.Builder(other);
  }
  
  /** Creates a new ExtraInfo RecordBuilder by copying an existing ExtraInfo instance */
  public static converTor.relayExtra.ExtraInfo.Builder newBuilder(converTor.relayExtra.ExtraInfo other) {
    return new converTor.relayExtra.ExtraInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for ExtraInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExtraInfo>
    implements org.apache.avro.data.RecordBuilder<ExtraInfo> {

    private java.lang.CharSequence nickname;
    private java.lang.CharSequence fingerprint;

    /** Creates a new Builder */
    private Builder() {
      super(converTor.relayExtra.ExtraInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(converTor.relayExtra.ExtraInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nickname)) {
        this.nickname = data().deepCopy(fields()[0].schema(), other.nickname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fingerprint)) {
        this.fingerprint = data().deepCopy(fields()[1].schema(), other.fingerprint);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ExtraInfo instance */
    private Builder(converTor.relayExtra.ExtraInfo other) {
            super(converTor.relayExtra.ExtraInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.nickname)) {
        this.nickname = data().deepCopy(fields()[0].schema(), other.nickname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fingerprint)) {
        this.fingerprint = data().deepCopy(fields()[1].schema(), other.fingerprint);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'nickname' field */
    public java.lang.CharSequence getNickname() {
      return nickname;
    }
    
    /** Sets the value of the 'nickname' field */
    public converTor.relayExtra.ExtraInfo.Builder setNickname(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.nickname = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'nickname' field has been set */
    public boolean hasNickname() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'nickname' field */
    public converTor.relayExtra.ExtraInfo.Builder clearNickname() {
      nickname = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'fingerprint' field */
    public java.lang.CharSequence getFingerprint() {
      return fingerprint;
    }
    
    /** Sets the value of the 'fingerprint' field */
    public converTor.relayExtra.ExtraInfo.Builder setFingerprint(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fingerprint = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'fingerprint' field has been set */
    public boolean hasFingerprint() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'fingerprint' field */
    public converTor.relayExtra.ExtraInfo.Builder clearFingerprint() {
      fingerprint = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ExtraInfo build() {
      try {
        ExtraInfo record = new ExtraInfo();
        record.nickname = fieldSetFlags()[0] ? this.nickname : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fingerprint = fieldSetFlags()[1] ? this.fingerprint : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
