/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package converTor.tordnsel;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ExitNode extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExitNode\",\"namespace\":\"converTor.tordnsel\",\"fields\":[{\"name\":\"fingerprint\",\"type\":[\"null\",\"string\"]},{\"name\":\"published\",\"type\":[\"null\",\"string\"]},{\"name\":\"last_status\",\"type\":[\"null\",\"string\"]},{\"name\":\"exit_list\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence fingerprint;
  @Deprecated public java.lang.CharSequence published;
  @Deprecated public java.lang.CharSequence last_status;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> exit_list;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ExitNode() {}

  /**
   * All-args constructor.
   */
  public ExitNode(java.lang.CharSequence fingerprint, java.lang.CharSequence published, java.lang.CharSequence last_status, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> exit_list) {
    this.fingerprint = fingerprint;
    this.published = published;
    this.last_status = last_status;
    this.exit_list = exit_list;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fingerprint;
    case 1: return published;
    case 2: return last_status;
    case 3: return exit_list;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fingerprint = (java.lang.CharSequence)value$; break;
    case 1: published = (java.lang.CharSequence)value$; break;
    case 2: last_status = (java.lang.CharSequence)value$; break;
    case 3: exit_list = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'fingerprint' field.
   */
  public java.lang.CharSequence getFingerprint() {
    return fingerprint;
  }

  /**
   * Sets the value of the 'fingerprint' field.
   * @param value the value to set.
   */
  public void setFingerprint(java.lang.CharSequence value) {
    this.fingerprint = value;
  }

  /**
   * Gets the value of the 'published' field.
   */
  public java.lang.CharSequence getPublished() {
    return published;
  }

  /**
   * Sets the value of the 'published' field.
   * @param value the value to set.
   */
  public void setPublished(java.lang.CharSequence value) {
    this.published = value;
  }

  /**
   * Gets the value of the 'last_status' field.
   */
  public java.lang.CharSequence getLastStatus() {
    return last_status;
  }

  /**
   * Sets the value of the 'last_status' field.
   * @param value the value to set.
   */
  public void setLastStatus(java.lang.CharSequence value) {
    this.last_status = value;
  }

  /**
   * Gets the value of the 'exit_list' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExitList() {
    return exit_list;
  }

  /**
   * Sets the value of the 'exit_list' field.
   * @param value the value to set.
   */
  public void setExitList(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.exit_list = value;
  }

  /** Creates a new ExitNode RecordBuilder */
  public static converTor.tordnsel.ExitNode.Builder newBuilder() {
    return new converTor.tordnsel.ExitNode.Builder();
  }
  
  /** Creates a new ExitNode RecordBuilder by copying an existing Builder */
  public static converTor.tordnsel.ExitNode.Builder newBuilder(converTor.tordnsel.ExitNode.Builder other) {
    return new converTor.tordnsel.ExitNode.Builder(other);
  }
  
  /** Creates a new ExitNode RecordBuilder by copying an existing ExitNode instance */
  public static converTor.tordnsel.ExitNode.Builder newBuilder(converTor.tordnsel.ExitNode other) {
    return new converTor.tordnsel.ExitNode.Builder(other);
  }
  
  /**
   * RecordBuilder for ExitNode instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExitNode>
    implements org.apache.avro.data.RecordBuilder<ExitNode> {

    private java.lang.CharSequence fingerprint;
    private java.lang.CharSequence published;
    private java.lang.CharSequence last_status;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> exit_list;

    /** Creates a new Builder */
    private Builder() {
      super(converTor.tordnsel.ExitNode.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(converTor.tordnsel.ExitNode.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fingerprint)) {
        this.fingerprint = data().deepCopy(fields()[0].schema(), other.fingerprint);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.published)) {
        this.published = data().deepCopy(fields()[1].schema(), other.published);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.last_status)) {
        this.last_status = data().deepCopy(fields()[2].schema(), other.last_status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exit_list)) {
        this.exit_list = data().deepCopy(fields()[3].schema(), other.exit_list);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ExitNode instance */
    private Builder(converTor.tordnsel.ExitNode other) {
            super(converTor.tordnsel.ExitNode.SCHEMA$);
      if (isValidValue(fields()[0], other.fingerprint)) {
        this.fingerprint = data().deepCopy(fields()[0].schema(), other.fingerprint);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.published)) {
        this.published = data().deepCopy(fields()[1].schema(), other.published);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.last_status)) {
        this.last_status = data().deepCopy(fields()[2].schema(), other.last_status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exit_list)) {
        this.exit_list = data().deepCopy(fields()[3].schema(), other.exit_list);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'fingerprint' field */
    public java.lang.CharSequence getFingerprint() {
      return fingerprint;
    }
    
    /** Sets the value of the 'fingerprint' field */
    public converTor.tordnsel.ExitNode.Builder setFingerprint(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.fingerprint = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'fingerprint' field has been set */
    public boolean hasFingerprint() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'fingerprint' field */
    public converTor.tordnsel.ExitNode.Builder clearFingerprint() {
      fingerprint = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'published' field */
    public java.lang.CharSequence getPublished() {
      return published;
    }
    
    /** Sets the value of the 'published' field */
    public converTor.tordnsel.ExitNode.Builder setPublished(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.published = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'published' field has been set */
    public boolean hasPublished() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'published' field */
    public converTor.tordnsel.ExitNode.Builder clearPublished() {
      published = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'last_status' field */
    public java.lang.CharSequence getLastStatus() {
      return last_status;
    }
    
    /** Sets the value of the 'last_status' field */
    public converTor.tordnsel.ExitNode.Builder setLastStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.last_status = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'last_status' field has been set */
    public boolean hasLastStatus() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'last_status' field */
    public converTor.tordnsel.ExitNode.Builder clearLastStatus() {
      last_status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'exit_list' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExitList() {
      return exit_list;
    }
    
    /** Sets the value of the 'exit_list' field */
    public converTor.tordnsel.ExitNode.Builder setExitList(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[3], value);
      this.exit_list = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'exit_list' field has been set */
    public boolean hasExitList() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'exit_list' field */
    public converTor.tordnsel.ExitNode.Builder clearExitList() {
      exit_list = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public ExitNode build() {
      try {
        ExitNode record = new ExitNode();
        record.fingerprint = fieldSetFlags()[0] ? this.fingerprint : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.published = fieldSetFlags()[1] ? this.published : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.last_status = fieldSetFlags()[2] ? this.last_status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.exit_list = fieldSetFlags()[3] ? this.exit_list : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
