/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.torproject.metrics.converTor.tordnsel;  
@SuppressWarnings("all")
/** tordnsel 1.0 */
@org.apache.avro.specific.AvroGenerated
public class Tordnsel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Tordnsel\",\"namespace\":\"org.torproject.metrics.converTor.tordnsel\",\"doc\":\"tordnsel 1.0\",\"fields\":[{\"name\":\"descriptor_type\",\"type\":\"string\",\"default\":\"tordnsel 1.0\"},{\"name\":\"downloaded\",\"type\":[\"null\",\"string\"]},{\"name\":\"exit_nodes\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ExitNode\",\"fields\":[{\"name\":\"fingerprint\",\"type\":[\"null\",\"string\"]},{\"name\":\"published\",\"type\":[\"null\",\"string\"]},{\"name\":\"last_status\",\"type\":[\"null\",\"string\"]},{\"name\":\"exit_list\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]}]}}]}],\"aliases\":[\"exitList\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence descriptor_type;
  @Deprecated public java.lang.CharSequence downloaded;
  @Deprecated public java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> exit_nodes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Tordnsel() {}

  /**
   * All-args constructor.
   */
  public Tordnsel(java.lang.CharSequence descriptor_type, java.lang.CharSequence downloaded, java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> exit_nodes) {
    this.descriptor_type = descriptor_type;
    this.downloaded = downloaded;
    this.exit_nodes = exit_nodes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return descriptor_type;
    case 1: return downloaded;
    case 2: return exit_nodes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: descriptor_type = (java.lang.CharSequence)value$; break;
    case 1: downloaded = (java.lang.CharSequence)value$; break;
    case 2: exit_nodes = (java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'descriptor_type' field.
   */
  public java.lang.CharSequence getDescriptorType() {
    return descriptor_type;
  }

  /**
   * Sets the value of the 'descriptor_type' field.
   * @param value the value to set.
   */
  public void setDescriptorType(java.lang.CharSequence value) {
    this.descriptor_type = value;
  }

  /**
   * Gets the value of the 'downloaded' field.
   */
  public java.lang.CharSequence getDownloaded() {
    return downloaded;
  }

  /**
   * Sets the value of the 'downloaded' field.
   * @param value the value to set.
   */
  public void setDownloaded(java.lang.CharSequence value) {
    this.downloaded = value;
  }

  /**
   * Gets the value of the 'exit_nodes' field.
   */
  public java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> getExitNodes() {
    return exit_nodes;
  }

  /**
   * Sets the value of the 'exit_nodes' field.
   * @param value the value to set.
   */
  public void setExitNodes(java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> value) {
    this.exit_nodes = value;
  }

  /** Creates a new Tordnsel RecordBuilder */
  public static org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder newBuilder() {
    return new org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder();
  }
  
  /** Creates a new Tordnsel RecordBuilder by copying an existing Builder */
  public static org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder newBuilder(org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder other) {
    return new org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder(other);
  }
  
  /** Creates a new Tordnsel RecordBuilder by copying an existing Tordnsel instance */
  public static org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder newBuilder(org.torproject.metrics.converTor.tordnsel.Tordnsel other) {
    return new org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder(other);
  }
  
  /**
   * RecordBuilder for Tordnsel instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Tordnsel>
    implements org.apache.avro.data.RecordBuilder<Tordnsel> {

    private java.lang.CharSequence descriptor_type;
    private java.lang.CharSequence downloaded;
    private java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> exit_nodes;

    /** Creates a new Builder */
    private Builder() {
      super(org.torproject.metrics.converTor.tordnsel.Tordnsel.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.descriptor_type)) {
        this.descriptor_type = data().deepCopy(fields()[0].schema(), other.descriptor_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.downloaded)) {
        this.downloaded = data().deepCopy(fields()[1].schema(), other.downloaded);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.exit_nodes)) {
        this.exit_nodes = data().deepCopy(fields()[2].schema(), other.exit_nodes);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Tordnsel instance */
    private Builder(org.torproject.metrics.converTor.tordnsel.Tordnsel other) {
            super(org.torproject.metrics.converTor.tordnsel.Tordnsel.SCHEMA$);
      if (isValidValue(fields()[0], other.descriptor_type)) {
        this.descriptor_type = data().deepCopy(fields()[0].schema(), other.descriptor_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.downloaded)) {
        this.downloaded = data().deepCopy(fields()[1].schema(), other.downloaded);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.exit_nodes)) {
        this.exit_nodes = data().deepCopy(fields()[2].schema(), other.exit_nodes);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'descriptor_type' field */
    public java.lang.CharSequence getDescriptorType() {
      return descriptor_type;
    }
    
    /** Sets the value of the 'descriptor_type' field */
    public org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder setDescriptorType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.descriptor_type = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'descriptor_type' field has been set */
    public boolean hasDescriptorType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'descriptor_type' field */
    public org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder clearDescriptorType() {
      descriptor_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'downloaded' field */
    public java.lang.CharSequence getDownloaded() {
      return downloaded;
    }
    
    /** Sets the value of the 'downloaded' field */
    public org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder setDownloaded(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.downloaded = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'downloaded' field has been set */
    public boolean hasDownloaded() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'downloaded' field */
    public org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder clearDownloaded() {
      downloaded = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'exit_nodes' field */
    public java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> getExitNodes() {
      return exit_nodes;
    }
    
    /** Sets the value of the 'exit_nodes' field */
    public org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder setExitNodes(java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode> value) {
      validate(fields()[2], value);
      this.exit_nodes = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'exit_nodes' field has been set */
    public boolean hasExitNodes() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'exit_nodes' field */
    public org.torproject.metrics.converTor.tordnsel.Tordnsel.Builder clearExitNodes() {
      exit_nodes = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Tordnsel build() {
      try {
        Tordnsel record = new Tordnsel();
        record.descriptor_type = fieldSetFlags()[0] ? this.descriptor_type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.downloaded = fieldSetFlags()[1] ? this.downloaded : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.exit_nodes = fieldSetFlags()[2] ? this.exit_nodes : (java.util.List<org.torproject.metrics.converTor.tordnsel.ExitNode>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
