/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.torproject.metrics.converTor.relayVote;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Policy extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Policy\",\"namespace\":\"org.torproject.metrics.converTor.relayVote\",\"fields\":[{\"name\":\"default_policy\",\"type\":[\"null\",\"string\"]},{\"name\":\"port_summary\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence default_policy;
  @Deprecated public java.lang.CharSequence port_summary;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Policy() {}

  /**
   * All-args constructor.
   */
  public Policy(java.lang.CharSequence default_policy, java.lang.CharSequence port_summary) {
    this.default_policy = default_policy;
    this.port_summary = port_summary;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return default_policy;
    case 1: return port_summary;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: default_policy = (java.lang.CharSequence)value$; break;
    case 1: port_summary = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'default_policy' field.
   */
  public java.lang.CharSequence getDefaultPolicy() {
    return default_policy;
  }

  /**
   * Sets the value of the 'default_policy' field.
   * @param value the value to set.
   */
  public void setDefaultPolicy(java.lang.CharSequence value) {
    this.default_policy = value;
  }

  /**
   * Gets the value of the 'port_summary' field.
   */
  public java.lang.CharSequence getPortSummary() {
    return port_summary;
  }

  /**
   * Sets the value of the 'port_summary' field.
   * @param value the value to set.
   */
  public void setPortSummary(java.lang.CharSequence value) {
    this.port_summary = value;
  }

  /** Creates a new Policy RecordBuilder */
  public static org.torproject.metrics.converTor.relayVote.Policy.Builder newBuilder() {
    return new org.torproject.metrics.converTor.relayVote.Policy.Builder();
  }
  
  /** Creates a new Policy RecordBuilder by copying an existing Builder */
  public static org.torproject.metrics.converTor.relayVote.Policy.Builder newBuilder(org.torproject.metrics.converTor.relayVote.Policy.Builder other) {
    return new org.torproject.metrics.converTor.relayVote.Policy.Builder(other);
  }
  
  /** Creates a new Policy RecordBuilder by copying an existing Policy instance */
  public static org.torproject.metrics.converTor.relayVote.Policy.Builder newBuilder(org.torproject.metrics.converTor.relayVote.Policy other) {
    return new org.torproject.metrics.converTor.relayVote.Policy.Builder(other);
  }
  
  /**
   * RecordBuilder for Policy instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Policy>
    implements org.apache.avro.data.RecordBuilder<Policy> {

    private java.lang.CharSequence default_policy;
    private java.lang.CharSequence port_summary;

    /** Creates a new Builder */
    private Builder() {
      super(org.torproject.metrics.converTor.relayVote.Policy.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.torproject.metrics.converTor.relayVote.Policy.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.default_policy)) {
        this.default_policy = data().deepCopy(fields()[0].schema(), other.default_policy);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.port_summary)) {
        this.port_summary = data().deepCopy(fields()[1].schema(), other.port_summary);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Policy instance */
    private Builder(org.torproject.metrics.converTor.relayVote.Policy other) {
            super(org.torproject.metrics.converTor.relayVote.Policy.SCHEMA$);
      if (isValidValue(fields()[0], other.default_policy)) {
        this.default_policy = data().deepCopy(fields()[0].schema(), other.default_policy);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.port_summary)) {
        this.port_summary = data().deepCopy(fields()[1].schema(), other.port_summary);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'default_policy' field */
    public java.lang.CharSequence getDefaultPolicy() {
      return default_policy;
    }
    
    /** Sets the value of the 'default_policy' field */
    public org.torproject.metrics.converTor.relayVote.Policy.Builder setDefaultPolicy(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.default_policy = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'default_policy' field has been set */
    public boolean hasDefaultPolicy() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'default_policy' field */
    public org.torproject.metrics.converTor.relayVote.Policy.Builder clearDefaultPolicy() {
      default_policy = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'port_summary' field */
    public java.lang.CharSequence getPortSummary() {
      return port_summary;
    }
    
    /** Sets the value of the 'port_summary' field */
    public org.torproject.metrics.converTor.relayVote.Policy.Builder setPortSummary(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.port_summary = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'port_summary' field has been set */
    public boolean hasPortSummary() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'port_summary' field */
    public org.torproject.metrics.converTor.relayVote.Policy.Builder clearPortSummary() {
      port_summary = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Policy build() {
      try {
        Policy record = new Policy();
        record.default_policy = fieldSetFlags()[0] ? this.default_policy : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.port_summary = fieldSetFlags()[1] ? this.port_summary : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
